### ISSUE TITLE
Can't re-order images

### ISSUE THREAD

**Issue by markdrechsler** [open-lms-open-source/moodle-mod_lightboxgallery#30]
Added in multiple images to the Lightbox, wanted to have them display in a specific order, but there's no way to move them around in the display order (that I can find anyway). Possible for a future release?

**Comment by tomschall** [comment]
At the moment sorting is guaranteed through the filname. It's possible to change the filename, when the file is uploaded. This way you can sort. But would be nice to have a drag and drop sorting feature.

**Comment by FurloSK** [comment]
Please, would this be possible? Reordering the images is basically a "must" when you have more images – otherwise, with any required change in their order, you have to start uploading the images from scratch.

Perhaps it would be possible to make order of images be dependant _not_ on **filename** (which is impossible to change after the upload), but on **caption text** instead? That way the order could be changed at least by renaming the picture. Thanks!

**Comment by aolley** [comment]
v4.0.6 now includes the ability to set a gallery to sort by the caption instead of the filename.

**Comment by FurloSK** [comment]
Wow, thank you!

Robert
